export const initialAppContext: AppContextType = {
    selectedPlaceId: null, 
    setSelectedPlaceId: () => {},
    allStyles: [],
    setAllStyles: () => {},
    stylesLoading: true,
    setStylesLoading: () => {},
    stylesLoaded: false,
    setStylesLoaded: () => {},
    catersTo: [],
    setCatersTo: () => {},
    catersToLoading: true,
    setCatersToLoading: () => {},
    catersToLoaded: false,
    setCatersToLoaded: () => {},
    placeTypes: [],
    setPlaceTypes: () => {},
    placeTypesLoading: true,
    setPlaceTypesLoading: () => {},
    placeTypesLoaded: false,
    setPlaceTypesLoaded: () => {},
    userPlaces: [],
    setUserPlaces: () => {},
    userPlacesLoading: true,
    setUserPlacesLoading: () => {},
    userPlacesLoaded: false,
    setUserPlacesLoaded: () => {},
    bookings: [],
    bookingsLoaded: false,
    bookingsLoading: true,
    setBookings: () => {},
    setBookingsLoaded: () => {},
    setBookingsLoading: () => {},
    placesViewStats: [],
    placesViewStatLoaded: false,
    placesViewStatLoading: true,
    setPlacesViewStats: () => {},
    setPlacesViewStatLoaded: () => {},
    setPlacesViewStatLoading: () => {},
    blogs: [],
    setBlogs: () => {},
    blogsLoaded: false,
    setBlogsLoaded: () => {},
    blogsLoading: true,
    setBlogsLoading: () => {},
    showMap: true,
    setShowMap: () => {},
    userBookedPlaces: [],
    mapKey: '',
    setMapKey: () => {},
    mapKeyLoaded: false,
    setMapKeyLoaded: () => {},
    mapKeyLoading: false,
    setMapKeyLoading: () => {},
    ageGroups: [],
    setAgeGroups: () => {},
    ageGroupsLoading: true,
    setAgeGroupsLoading: () => {},
    ageGroupsLoaded: false,
    setAgeGroupsLoaded: () => {},
    resetUserInfoInContext: () => {},
}